pentatrion_vite:
    # Set attributes that will be rendered on all script and link tags
    script_attributes:
        defer: true
        referrerpolicy: origin
        # Uncomment (also under link_attributes) if using Turbo Drive
        # https://turbo.hotwired.dev/handbook/drive#reloading-when-assets-change
        #'data-turbo-track': reload
    link_attributes:
        referrerpolicy: origin
    # Uncomment if using Turbo Drive
    #'data-turbo-track': reload

    preload_attributes:
        referrerpolicy: origin

    # If using Encore.enableIntegrityHashes() and need the crossorigin attribute (default: false, or use 'anonymous' or 'use-credentials')
    # crossorigin: 'anonymous'

    # Preload all rendered script and link tags automatically via the HTTP/2 Link header
    # preload: true

    # Throw an exception if the entrypoints.json file is missing or an entry is missing from the data
    # strict_mode: false

when@prod:
    pentatrion_vite:
        # Cache the entrypoints.json and manifest.json
        cache: true
