pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    blog_preview_image:
                        items: {  }
                        medias: {  }
                        name: blog_preview_image
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1741267520
                        creationDate: 1741267509
                        preserveAnimation: false
