pimcore:
    assets:
        image:
            thumbnails:
                definitions:
                    project_preview_image:
                        items: {}
                        medias: {}
                        name: project_preview_image
                        description: ''
                        group: ''
                        format: SOURCE
                        quality: 85
                        highResolution: null
                        preserveColor: false
                        preserveMetaData: false
                        rasterizeSVG: false
                        downloadable: false
                        modificationDate: 1741274783
                        creationDate: 1741274783
                        preserveAnimation: false
